name: mapa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: 2.6.1
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  google_fonts: 6.1.0
  font_awesome_flutter: 10.3.0
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.17.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  cached_network_image: ^3.3.1
  http: ^1.2.1
  image: ^4.1.7
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/icons/ 
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Raleway
      fonts: 
        - asset: assets/fonts/Raleway-Black.ttf