// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmcNvdg-rL2uoU5Xm5Dii4UtrPAJFRHY',
    appId: '1:1024851096672:web:16c1f42ced1a14e736ff05',
    messagingSenderId: '1024851096672',
    projectId: 'mapa-55d61',
    authDomain: 'mapa-55d61.firebaseapp.com',
    storageBucket: 'mapa-55d61.appspot.com',
    measurementId: 'G-8HJH6QF41X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZIpbXnHqXgooH85TIAORsPRg8I6mKj9E',
    appId: '1:1024851096672:android:3b6be39fc05ebd2136ff05',
    messagingSenderId: '1024851096672',
    projectId: 'mapa-55d61',
    storageBucket: 'mapa-55d61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDGnyrF_1RSwU4ZRvzhVXAoBX19CNYNBg',
    appId: '1:1024851096672:ios:1e4a959bb0a8f83836ff05',
    messagingSenderId: '1024851096672',
    projectId: 'mapa-55d61',
    storageBucket: 'mapa-55d61.appspot.com',
    iosClientId: '1024851096672-2lolsq3h2heggp7vnqkc3bam7in9l8h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDGnyrF_1RSwU4ZRvzhVXAoBX19CNYNBg',
    appId: '1:1024851096672:ios:1e4a959bb0a8f83836ff05',
    messagingSenderId: '1024851096672',
    projectId: 'mapa-55d61',
    storageBucket: 'mapa-55d61.appspot.com',
    iosClientId: '1024851096672-2lolsq3h2heggp7vnqkc3bam7in9l8h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlmcNvdg-rL2uoU5Xm5Dii4UtrPAJFRHY',
    appId: '1:1024851096672:web:906bf9162fe0021e36ff05',
    messagingSenderId: '1024851096672',
    projectId: 'mapa-55d61',
    authDomain: 'mapa-55d61.firebaseapp.com',
    storageBucket: 'mapa-55d61.appspot.com',
    measurementId: 'G-RJEFHRXHL6',
  );
}
